modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="AGPL-3.0"
issueTrackerURL="https://github.com/Bismuth-Software/Bon-Appetit/issues" #optional

[[mods]] #mandatory
modId="bonappetit" #mandatory
version="0.1.0-21.1" #mandatory
displayName="Bon App√©tit" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

displayURL="https://modrinth.com/mod/bon-appetit/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="cubicroot.png" #optional

credits="DynoMyte6277" #optional
authors="Ashley, AgentPillow" #optional
description='''Food ;3'''

[[mixins]]
config="bonappetit.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bonappetit]] #optional
    modId="neoforge" #mandatory
    # The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
    type="required" #mandatory
    # Optional field describing why the dependency is required or why it is incompatible
    # reason="..."
    versionRange="[${neo_version},)" #mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"

[[dependencies.bonappetit]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[features.bonappetit]
openGLVersion="[3.2,)"
